### ISSUE TITLE
Upgrading rest-client from 2.0.2 to 2.1.0 breaks lots of requests with change in utf-8 encoding

### ISSUE THREAD

**Issue by tomurb** [chargebee/chargebee-ruby#50] opened 2020-11-03 14:46 UTC
Just in case you're not aware
https://github.com/rest-client/rest-client/issues/740#

I had to set rest-client in my Gemfile to 2.0.2 to avoid this issue.

**Comment by scottbarrow** [comment] 2021-06-10 00:37
An update today from chargebee (2.8.5) to chargebee (2.8.6) changed
-    rest-client (2.0.2)
+    rest-client (2.1.0)

This now breaks a lot of encoding as per this issue

**Comment by cb-rakesh** [comment] 2021-06-10 03:12
1) Version update 2.8.6 doesn't deal with any changes to the dependency rest-client.
2) The rest-client was added as dependancy '>= 1.8', '< 3.0'  and this change happened 4 years ago.

> An update today from chargebee (2.8.5) to chargebee (2.8.6) changed
> -rest-client (2.0.2)
> +rest-client (2.1.0)
> 
> This now breaks a lot of encoding as per this issue

**Comment by scottbarrow** [comment] 2021-06-10 16:07
> 1. Version update 2.8.6 doesn't deal with any changes to the dependency rest-client.
> 2. The rest-client was added as dependancy '>= 1.8', '< 3.0'  and this change happened 4 years ago.

My git dif begs to differ, this is `bundle update chargbee` taking 2.8.5 to 2.8.6, you can see that the rest-client bumps from 2.0.2 to 2.1.0 which has a minor version change, however it was actually a major change

![Screen Shot 2021-06-10 at 9 05 12 AM](https://user-images.githubusercontent.com/5571736/121558961-fbcc9e80-c9ca-11eb-977e-8b654202e876.png)

**Comment by cb-rakesh** [comment] 2021-06-14 07:40
@scottbarrow I'm looking into this. Will give you an update soon.

**Comment by cb-rakesh** [comment] 2021-07-22 05:26
This has been fixed with version 2.8.7.

**Closed** 2021-07-22 05:26 UTC

**Comment by loomchild** [comment] 2024-09-08 12:31
@tomurb Sorry for contacting you after such a long time, but I am trying to upgrade rest-client and can't reproduce the issue. Could you share the reproduction steps and the environment used?

**Comment by cb-alish** [comment] 2024-09-08 13:08
Hi @loomchild, please refer to this [comment](https://github.com/chargebee/chargebee-ruby/issues/43#issuecomment-2336679799) once.
